### ISSUE TITLE
'j0': The POSIX name for this item is deprecated. (VS2015)

### ISSUE THREAD

**Issue by kkc0923** [ceres-solver/ceres-solver#190]
Hi. I tested 1.11.0 on VS 2015 and got some errors in Jet.h

Error	C4996	'j0': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _j0. See online help for details.	XXXXX\include\ceres\jet.h
Error	C4996	'j1': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _j1. See online help for details.	XXXXX\include\ceres\jet.h
Error	C4996	'jn': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _jn. See online help for details.	XXXXX\include\ceres\jet.h

I simply renamed j0, j1 and jn to _j0, _j1 and _jn on Jet.h (line 489~491) and the error is disappeared.

**Comment by sandwichmaker** [comment]
I do not have a windows compiler to test the fix with, I will need to look into what the naming story for these functions is across platforms before fixing this.

**Comment by hpp340** [comment]
Maybe you can fix the error by adding  _CRT_NONSTDC_NO_DEPRECATE to the preprocessor definitions.

**Comment by alexsmac** [comment]
This should be fixed by this CL: https://ceres-solver-review.googlesource.com/#/c/7490/

Please can you confirm if it does.

**Comment by fschmi** [comment]
@alexsmac thank you for the fix. I think you forgot to correct the corresponding else statements though (line 518. 525 & 532).

**Comment by alexsmac** [comment]
@fschmi - what do you mean?  The #else statements are only compiled on non-MSVC systems (or on older MSVC systems where the new functions are not defined).  Contrary to the error message from MSVC, as far as I know, the POSIX standard does *not* use underscore prefixes, they are Microsoft-specific.

**Comment by ShiwenH** [comment]
@hpp340 you fix my problem. Thanks.
