### ISSUE TITLE
error: cannot convert ‘int*’ to ‘idx_t*’ {aka ‘long int*’}

### ISSUE THREAD

**Issue by jiapei-nexera** [ceres-solver/ceres-solver#828]
Where to set `CERES_NO_METIS =  true` ?

Otherwise, I'll have the following **ERROR** message

```console
....../ceres-solver/internal/ceres/eigensparse.cc:138:21:   required from ‘ceres::internal::LinearSolverTerminationType ceres::internal::EigenSparseCholeskyTemplate<Solver>::Factorize(ceres::internal::CompressedRowSparseMatrix*, std::string*) [with Solver = Eigen::SimplicialLDLT<Eigen::SparseMatrix<double>, 2, Eigen::MetisOrdering<int> >; std::string = std::__cxx11::basic_string<char>]’
....../ceres-solver/internal/ceres/eigensparse.cc:114:31:   required from here
/usr/include/eigen3/Eigen/src/MetisSupport/MetisSupport.h:112:35: error: cannot convert ‘int*’ to ‘idx_t*’ {aka ‘long int*’}
  112 |      output_error = METIS_NodeND(&m, m_indexPtr.data(), m_innerIndices.data(), NULL, NULL, perm.data(), iperm.data());
      |                                   ^
      |                                   |
      |                                   int*
In file included from /usr/include/eigen3/Eigen/MetisSupport:16,
                 from ....../ceres-solver/internal/ceres/eigensparse.cc:42:
/opt/SuiteSparse/include/metis.h:246:36: note:   initializing argument 1 of ‘int METIS_NodeND(idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, idx_t*, idx_t*)’
```

**Comment by sandwichmaker** [comment]
please do not use ceres at head right now, use a stable version(version 2.1) while the build is broken.

**Comment by sandwichmaker** [comment]
this should be fixed at head now. you can disable metis use in eigen setting EIGENMETIS=OFF.

**Comment by StefanBruens** [comment]
IMHO this is still relevant, and not really fixed.

`metis.h` provides an `IDXTYPEWIDTH` `#define`. If this is set to 64, `idx_t` is typedef'ed to int64_t.

On the other hand, the code in eigensparse.cc  
https://github.com/ceres-solver/ceres-solver/blob/c29b5257e23f91d6a47c4db9d57350ed4985ea46/internal/ceres/eigensparse.cc#L165
uses `int` as the index type.
