### ISSUE TITLE
`-Wfree-nonheap-object` warnings in LTO builds

### ISSUE THREAD

**Issue by sergiud** [ceres-solver/ceres-solver#867]
Ceres Solver compiled with GCC 12.1.1 and `-flto=auto` flag issues the following warning in release builds:
```
In member function ‘deallocate’,
    inlined from ‘deallocate’ at /usr/include/c++/12.1.1/bits/alloc_traits.h:496:23,
    inlined from ‘__dt_base ’ at /home/sergiu/Projects/ceres-solver/include/ceres/internal/fixed_array.h:423:36,
    inlined from ‘__dt_base ’ at /home/sergiu/Projects/ceres-solver/include/ceres/internal/fixed_array.h:167:3,
    inlined from ‘EvaluateJacobianForParameterBlock’ at /home/sergiu/Projects/ceres-solver/include/ceres/internal/numeric_diff.h:170:3,
    inlined from ‘Apply’ at /home/sergiu/Projects/ceres-solver/include/ceres/internal/numeric_diff.h:462:52,
    inlined from ‘Evaluate’ at /home/sergiu/Projects/ceres-solver/include/ceres/numeric_diff_cost_function.h:239:46:
/usr/include/c++/12.1.1/bits/new_allocator.h:158:33: warning: ‘operator delete’ called on unallocated object ‘residual_array’ [-Wfree-nonheap-object]
  158 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
```
Looking at the `FixedArray` implementation, the reason for the warning seems to be the logic for differentiating between the statically and dynamically allocated buffers. While the static buffer is identified only through its size which can only be determined at runtime, additional code paths are generated that would cause the static buffer to be deallocated dynamically (even though unlikely to be actually executed).

To eliminate the warning, the two memory buffers should ideally be determined through a flag to reduce the number of possible states to exactly two, maybe also by storing the static buffer and the pointer to the dynamic buffer in a union (similar to `std::variant`).

**Comment by sandwichmaker** [comment]
we should be able to fix this by moving to absl and using the more up to date implementation there I think.

**Comment by sandwichmaker** [comment]
@sergiud this should be fixed now no?

**Comment by sandwichmaker** [comment]
Could you check and close this bug if appropriate?

**Comment by sergiud** [comment]
Unfortunately, the issue is still present with GCC 14.2.1 and Ceres at head (01a06ef7b1d9b59bc889f8686b949772523578bf):
```console
/usr/include/eigen3/Eigen/src/Core/ProductEvaluators.h:29: note: a type with different bases is defined in another translation unit
   29 | struct evaluator<Product<Lhs, Rhs, Options> >
[788/969] Linking CXX executable bin/numeric_diff_cost_function_test
In member function ‘deallocate’,
    inlined from ‘deallocate’ at /usr/include/c++/14.2.1/bits/alloc_traits.h:513:23,
    inlined from ‘__dt_base ’ at /home/sergiu/Projects/ceres-solver/third_party/abseil-cpp/absl/container/fixed_array.h:481:36,
    inlined from ‘__dt_base ’ at /home/sergiu/Projects/ceres-solver/third_party/abseil-cpp/absl/container/fixed_array.h:174:3,
    inlined from ‘EvaluateJacobianForParameterBlock’ at /home/sergiu/Projects/ceres-solver/include/ceres/internal/numeric_diff.h:170:3,
    inlined from ‘Apply’ at /home/sergiu/Projects/ceres-solver/include/ceres/internal/numeric_diff.h:462:52,
    inlined from ‘Evaluate’ at /home/sergiu/Projects/ceres-solver/include/ceres/numeric_diff_cost_function.h:262:47:
/usr/include/c++/14.2.1/bits/new_allocator.h:172:33: warning: ‘operator delete’ called on unallocated object ‘residual_array’ [-Wfree-nonheap-object]
  172 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |                                 ^
/home/sergiu/Projects/ceres-solver/include/ceres/internal/numeric_diff.h: In member function ‘Evaluate’:
/home/sergiu/Projects/ceres-solver/include/ceres/internal/numeric_diff.h:129:30: note: declared here
  129 |     absl::FixedArray<double> residual_array(num_residuals_internal);
      |                              ^
In member function ‘deallocate’,
    inlined from ‘deallocate’ at /usr/include/c++/14.2.1/bits/alloc_traits.h:513:23,
    inlined from ‘__dt_base ’ at /home/sergiu/Projects/ceres-solver/third_party/abseil-cpp/absl/container/fixed_array.h:481:36,
    inlined from ‘__dt_base ’ at /home/sergiu/Projects/ceres-solver/third_party/abseil-cpp/absl/container/fixed_array.h:174:3,
    inlined from ‘EvaluateJacobianForParameterBlock’ at /home/sergiu/Projects/ceres-solver/include/ceres/internal/numeric_diff.h:170:3,
    inlined from ‘Apply’ at /home/sergiu/Projects/ceres-solver/include/ceres/internal/numeric_diff.h:462:52,
    inlined from ‘Evaluate’ at /home/sergiu/Projects/ceres-solver/include/ceres/numeric_diff_cost_function.h:262:47:
/usr/include/c++/14.2.1/bits/new_allocator.h:172:33: warning: ‘operator delete’ called on unallocated object ‘residual_array’ [-Wfree-nonheap-object]
  172 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |                                 ^
/home/sergiu/Projects/ceres-solver/include/ceres/internal/numeric_diff.h: In member function ‘Evaluate’:
/home/sergiu/Projects/ceres-solver/include/ceres/internal/numeric_diff.h:129:30: note: declared here
  129 |     absl::FixedArray<double> residual_array(num_residuals_internal);
      |   
```

**Comment by sandwichmaker** [comment]
Well in that case this seems more like an absl bug rather than a ceres bug at this point no?

**Comment by sergiud** [comment]
Either that or a compiler issue. I reported abseil/abseil-cpp#1843.
