### ISSUE TITLE
Remove OPENMP and NO_THREADS as threading backends

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#886]
With @DmitriyKorchemkin's ParallelFor changes and C++17 being the standard model we are compiling with there is no reason to keep these two backends in place. They are not really tested or optimized. There should be no penality for not using the threads anymore (mutex costs remain the same). OpenMP seems to be mildly slower than CXX threads also.

```
./bin/bundle_adjuster --input ${HOME}/bal_problems/problem-744-543562-pre.txt

OpenMP:
Preprocessor 17.609368

Residual only evaluation 1.727921 (5)
Jacobian & residual evaluation 6.731878 (6)
Linear solver 36.640296 (5)
Minimizer 49.505668

Postprocessor 0.286242
Total 67.401280

CXX:
Preprocessor 17.996831

Residual only evaluation 0.518822 (5)
Jacobian & residual evaluation 7.362002 (6)
Linear solver 34.516102 (5)
Minimizer 46.748151

Postprocessor 0.285872
Total 65.030854

./bin/bundle_adjuster --input ${HOME}/bal_problems/problem-951-708276-pre.txt
OpenMP
Preprocessor 23.855088

Residual only evaluation 2.528524 (5)
Jacobian & residual evaluation 8.800000 (5)
Linear solver 57.068341 (5)
Minimizer 73.529374

Postprocessor 0.365246
Total 97.749709

CXX:
Preprocessor 23.893380

Residual only evaluation 0.556834 (5)
Jacobian & residual evaluation 6.941720 (5)
Linear solver 54.890267 (5)
Minimizer 67.108281

Postprocessor 0.351945
Total 91.353606
```

**Comment by sandwichmaker** [comment]
cc: @DmitriyKorchemkin

**Comment by DmitriyKorchemkin** [comment]
@sandwichmaker , OpenMP backend was limited in performance by `dynamic` scheduling and calling `omp_get_thread_num` via `TokenProvider` on each iteration.

This was fixed in the 4th patchset of CL under discussion, and now OpenMP backend is one of the fastest implementations, so the choice is not that simple in my opinion.
![speedup](https://user-images.githubusercontent.com/6394216/191093072-a3b0f90b-dd54-46a1-a5cd-e870c1951902.png)

**Comment by sandwichmaker** [comment]
Thats a fair observation, there is no rush to remove anything I was just hoping for simplification. I think we can still get rid of the no_threads backend. Lets come back to this once the c++ threading improvements are all done and stable and see if the extra effort to maintain the openmp backend is worth it.

**Comment by sandwichmaker** [comment]
The discussion and benchmarks on https://ceres-solver-review.googlesource.com/c/ceres-solver/+/23140 indicates that
at this point the difference between c++ threads and openmp is not particularly large and we will reduce complexity by making it the one option and working to optimize it.

I would like to come to a decision here and resolve this soonish.
